let flashingInterval = null;

function drawPyramid(color) {
    const rows = parseInt(document.getElementById('rows').value);
    const output = document.getElementById('output');

    output.innerHTML = ''; 

    for (let i = 1; i <= rows; i++) {
        const row = document.createElement('div');
        row.className = 'row';

        for (let j = 0; j < i; j++) {
            const bulb = document.createElement('div');
            bulb.className = 'bulb';
            bulb.style.backgroundColor = "white"; 
            bulb.style.margin = "10px";
            row.appendChild(bulb);
        }

        output.appendChild(row);
    }
}

function flashBulb() {
    stopFlashing(); 

    const color = document.getElementById('color').value;
    drawPyramid(color); 

    const bulbs = document.querySelectorAll('.bulb');
    let index = 0;

    flashingInterval = setInterval(() => {
        bulbs.forEach(bulb => {
            bulb.style.boxShadow = ''; 
            bulb.style.backgroundColor='white'
        }); 

        if (bulbs[index]) {
            bulbs[index].style.boxShadow = `0 0 20px ${color}`; // Flash color
            bulbs[index].style.backgroundColor=color;
        }

        index = (index + 1) % bulbs.length; 
    }, 500); 
}

function stopFlashing() {
    if (flashingInterval !== null) {
        clearInterval(flashingInterval);
        flashingInterval = null;
    }

    document.querySelectorAll('.bulb').forEach(bulb => {
        bulb.style.boxShadow = ''; 
    });
}






  
   
                            
          
        
      
       
     
    
    
                                                                                                                                   
    
                          
                                 
                                                                                                                                                
  
                      
                    
    
    
    
        
    
      
   
              
           
           
                             
          



   

              
   
    
   

    

    

   

   



       
      
     

     
       
        
            

   
   
  
    
   
  
  
    
      
 
    
   
    
   
    
     
    
   
 
    
   
                   
      
           
           
     
      
    
   
                                    

                   
      
                 
          
                                   
                            
                     
             
                                                                                                                          

          
   
            
          
              
                
               
            
                             
       
        
      
           
     
                                                        
      
                                                                                 
        
        
      
          
   
          
      
       
   
     
    
    
     
                            
     
             
       
    
       
        
     
   
     
      
      
          
                
                                   
     
   
   
 
    
       
              
               
                 
            
         
     
        
       
       
        
 
 


 

 
      
      
     
     
    
     
   
   
    
         
        
       
               
     
    
    
     
     
     
       


    
    
   
     
    
       
    
       
    
   
 
      


   

   
       
    
   
    
   

    
    
    
   
    
     
   
    
    
    
   
    
    
      
   
                            
            

         
                         
     
      
      
          
    
 
  
     
      
      
    
    
    
     
    
     
    

   
     
     
   
      
       
        
      
       
       
          
                
                            
        
               
        
           

                  
 
        
            
                
                                                        
                             
                    
       
             
                 
                            
               
                                           
                                           
                                   
                                             
                                            
                                          

                      
                           
                         
     
        
       
                 
                       
  
                    
                            
              


 
   
    
    
        
      
         
         
     
        
        
                  
                            
                                      
                                                          

             
                     
                       
       
                                  
                  
                     
                        
                                                        
                                               
                                        
                                                        
                                                            
                                                                  
                                                        
                                                 
                  
      
                                
                   
                 
   
                                                
                      
                             
                       
              
                     

        
                                            
                                    
                                       
                                                     
                                        
     
                  
          
                            
                      
                           
                                               
                       
                                   
                                     
                                                  
                                                 
                                                           
                  
                        
                                        
                            
                                                        
                                                           
                    
                                                                      
                                         
                                          
                                
                          
                    

                  
                             
                               
                                                                        
                           
                                      
                                

                                                           
                                  
                         
                                       
                                                                

                                                  
                                                         
                                                          
                                                                    
                                                              
                                                          
                                                            
                                                               
                                                            

                                          
                        
                      
                                            
                                           
                                                
                                                         
                                             
                                      
                                              

                                           
                                      
                                          

                                                     
                                                                   

                                
                   
                         
                         
                          
                                       
                                                   
                                         
                                           
                                                                  
                                
            
                     
                   
               
                             
                            
                                      
                                                              
                                      
                                                         
                                                                                     
                                                                             
          
                       
                          
                       
                    
                       
                            
                                         
                                          
                        
                       
                              
                     
                         
                   
                           
                            
               
                          
                           
                                         
                                                  
                                  
                                                                 
                              
                                  
                                     
                      
                                 
                           
                                         
                                            
                                         
                             
                             
                               
                  
                          
                               
                            
                                  
                                 
                                
                              
                         
                                          
                      
                               
                     
                                   
                          
                             
                                              
                  
                      
                
                           
                            
                
                    
                      
                           
                                    
                           
                                                     


                         
                                 
                   
                             
                       
                           
                     
                   
          
                     
                                    
                                        
                                                                     
                      
                          
                        
                                    
                                       
                                   
                              
                                     
                                                     
                                           
                                                      
                                            
                                                                                 
                                                
                                        
                
                                               
                     
                       
                             
                          
                           
                          

                                                 
                                
                        
                            
                       
                                       
                                  
                                 
                                         
                              
                                                        
                                                                  
                                                         
                                                   
                                
                                  
                   
                        
                     
                       

                                   